export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const CLEAR_CART = 'CLEAR_CART'
export const INCREASE_CART = 'INCREASE_CART'
export const DECREASE_CART = 'DECREASE_CART'